apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 150-ibm-production-vpc-openshift
  labels:
    type: infrastructure
    platform: ibm
    code: '150'
  annotations:
    displayName: IBM Production VPC OpenShift
    description: >-
      IBM VPC with Red Hat OpenShift cluster for production and VPC Transit
      Gateway to development VPC
spec:
  modules:
    - name: ibm-resource-group
      alias: kms_resource_group
      version: v3.2.15
    - name: ibm-resource-group
      alias: integration_resource_group
      version: v3.2.15
      default: true
    - name: ibm-resource-group
      alias: cs_resource_group
      version: v3.2.15
    - name: ibm-activity-tracker
      alias: ibm-activity-tracker
      version: v2.4.15
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-cloud-monitoring
      alias: sysdig
      version: v4.1.2
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-cloud-monitoring-bind
      alias: sysdig-bind
      version: v1.3.4
    - name: ibm-flow-logs
      alias: ibm-flow-logs
      version: v1.0.1
      dependencies:
        - name: target
          ref: ibm-vpc
        - name: cos_bucket
          ref: flow_log_bucket
    - name: ibm-kms
      alias: kms
      version: v0.3.4
      variables:
        - name: provision
          value: false
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
          value: ''
      dependencies:
        - name: resource_group
          ref: kms_resource_group
    - name: ibm-kms-key
      alias: kms-key
      version: v1.5.2
      variables:
        - name: provision
          value: true
      dependencies:
        - name: kms
          ref: kms
    - name: ibm-log-analysis
      alias: logdna
      version: v4.1.2
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-log-analysis-bind
      alias: ibm-logdna-bind
      version: v1.3.5
    - name: ibm-object-storage
      alias: cos
      version: v4.0.3
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-vpc-subnets
      alias: vpe-subnets
      version: v1.13.2
      variables:
        - name: _count
          value: 3
        - name: label
          value: vpe
        - name: ipv4_cidr_blocks
          value:
            - 10.40.20.0/24
            - 10.50.20.0/24
            - 10.60.20.0/24
    - name: ibm-ocp-vpc
      alias: integration_cluster
      version: v1.15.4
      variables:
        - name: disable_public_endpoint
          value: true
        - name: kms_enabled
          value: true
        - name: worker_count
          alias: integration_worker_count
        - name: ocp_version
          value: 4.8
      dependencies:
        - name: subnets
          ref: worker-subnets
        - name: kms_key
          ref: kms_key
    - name: ibm-vpc
      alias: ibm-vpc
      version: v1.16.0
      variables:
        - name: address_prefix_count
          value: 3
        - name: address_prefixes
          value:
            - 10.40.0.0/18
            - 10.50.0.0/18
            - 10.60.0.0/18
    - name: ibm-object-storage-bucket
      alias: flow_log_bucket
      version: v0.8.3
      variables:
        - name: label
          value: flow-logs
        - name: allowed_ip
          value:
            - 0.0.0.0/0
    - name: ibm-vpc-gateways
      alias: ibm-vpc-gateways
      version: v1.9.0
    - name: ibm-vpc-subnets
      alias: worker-subnets
      version: v1.13.2
      variables:
        - name: _count
          alias: workload_worker_subnet_count
          scope: global
          value: 3
        - name: label
          value: worker
        - name: ipv4_cidr_blocks
          value:
            - 10.40.10.0/24
            - 10.50.10.0/24
            - 10.60.10.0/24
      dependencies:
        - name: gateways
          ref: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      alias: ingress-subnets
      version: v1.13.2
      variables:
        - name: _count
          value: 3
        - name: label
          value: ingress
        - name: ipv4_cidr_blocks
          value:
            - 10.40.30.0/24
            - 10.50.30.0/24
            - 10.60.30.0/24
    - name: ibm-vpe-gateway
      alias: vpe-cos
      version: v1.6.1
      dependencies:
        - name: resource
          ref: cos
        - name: subnets
          ref: vpe-subnets
        - name: sync
          ref: integration_cluster
    - name: ibm-transit-gateway
      alias: ibm-transit-gateway
      version: v0.2.2
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource-group
          ref: cs_resource_group
        - name: connections
          ref: ibm-vpc
  variables:
    - name: ibmcloud_api_key
      type: string
      description: The IBM Cloud api key
    - name: kms_resource_group_name
      type: string
      description: The name of the resource group
    - name: region
      type: string
    - name: integration_resource_group_name
      type: string
      description: The name of the resource group
    - name: cs_resource_group_name
      type: string
      description: The name of the resource group
    - name: kms_region
      type: string
      description: Geographic location of the resource (e.g. us-south, us-east)
    - name: vpe-subnets__count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 3
    - name: integration_worker_count
      type: number
      description: >-
        The number of worker nodes that should be provisioned for classic
        infrastructure
      defaultValue: 3
    - name: integration_cluster_flavor
      type: string
      description: The machine type that will be provisioned for classic infrastructure
      defaultValue: bx2.4x16
    - name: workload_worker_subnet_count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 3
    - name: ingress-subnets__count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 3
