apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 110-ibm-vpc-edge-standard
  labels:
    type: infrastructure
    platform: ibm
    code: '110'
  annotations:
    displayName: IBM VPC OpenShift Standard
    description: IBM VPC with VPN, Bastion servers, and OpenShift
    vpn/required: 'false'
spec:
  modules:
    - name: ibm-activity-tracker
      alias: ibm-activity-tracker
      version: v2.4.17
    - name: ibm-flow-logs
      alias: ibm-flow-logs
      version: v1.0.3
      dependencies:
        - name: target
          ref: ibm-vpc
        - name: cos_bucket
          ref: flow_log_bucket
    - name: ibm-kms
      alias: kms
      version: v0.3.6
      variables:
        - name: provision
          value: false
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
          value: ''
      dependencies:
        - name: resource_group
          ref: kms_resource_group
    - name: ibm-kms-key
      alias: cos_key
      version: v1.5.3
      default: true
      variables:
        - name: provision
          value: true
      dependencies:
        - name: kms
          ref: kms
    - name: ibm-resource-group
      alias: kms_resource_group
      version: v3.3.4
      variables:
        - name: provision
          value: false
    - name: ibm-resource-group
      alias: vpc_resource_group
      version: v3.3.4
      default: true
    - name: ibm-resource-group
      alias: cs_resource_group
      version: v3.3.4
      variables:
        - name: provision
          value: false
    - name: ibm-object-storage
      alias: cos
      version: v4.1.0
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-object-storage-bucket
      alias: flow_log_bucket
      version: v0.8.4
      variables:
        - name: label
          value: flow-logs
        - name: allowed_ip
          value:
            - 0.0.0.0/0
    - name: ibm-secrets-manager
      alias: ibm-secrets-manager
      version: v1.0.2
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-vpc
      alias: ibm-vpc
      version: v1.17.0
      variables:
        - name: address_prefix_count
          value: 3
        - name: address_prefixes
          value:
            - 10.1.0.0/20
            - 10.2.0.0/20
            - 10.3.0.0/20
    - name: ibm-vpc-gateways
      alias: ibm-vpc-gateways
      version: v1.10.0
    - name: ibm-vpc-subnets
      alias: ingress-subnets
      version: v1.14.0
      variables:
        - name: _count
          value: 3
        - name: label
          value: ingress
        - name: ipv4_cidr_blocks
          value:
            - 10.1.0.0/26
            - 10.2.0.0/26
            - 10.3.0.0/26
      dependencies:
        - name: gateways
          ref: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      alias: egress-subnets
      version: v1.14.0
      variables:
        - name: _count
          value: 3
        - name: label
          value: egress
        - name: ipv4_cidr_blocks
          value:
            - 10.1.0.128/26
            - 10.2.0.128/26
            - 10.3.0.128/26
    - name: ibm-vpn-server
      alias: ibm-vpn-server
      version: v0.2.1
      dependencies:
        - name: subnets
          ref: ingress-subnets
        - name: ibm-secrets-manager
          ref: secrets-manager
      variables:
        - name: vpn_client_timeout
          value: 3600
  variables:
    - name: ibmcloud_api_key
      type: string
      description: The IBM Cloud api key
    - name: region
      type: string
      description: Geographic location of the resource (e.g. us-south, us-east)
    - name: kms_region
      type: string
      description: Geographic location of the resource (e.g. us-south, us-east)
    - name: vpc_name_prefix
      type: string
      description: >-
        The name_prefix used to build the name if one is not provided. If used
        the name will be `{name_prefix}-{label}`
      defaultValue: base
    - name: kms_resource_group_name
      type: string
      description: The name of the resource group
    - name: vpc_resource_group_name
      type: string
      description: The name of the resource group
    - name: cs_resource_group_name
      type: string
      description: The name of the resource group
    - name: common_tags
      type: list(string)
      description: Common tags that should be added to the instance
      defaultValue: []
    - name: ingress-subnets__count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 3
    - name: egress-subnets__count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 3
