apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 110-ibm-vpc-edge-standard
  labels:
    type: infrastructure
    platform: ibm
    code: '110'
  annotations:
    displayName: IBM VPC OpenShift Standard
    description: IBM VPC with VPN, Bastion servers, and OpenShift
spec:
  modules:
    - name: ibm-resource-group
      alias: kms_resource_group
      version: v3.2.15
      variables:
        - name: provision
          value: false
    - name: ibm-resource-group
      alias: vpc_resource_group
      version: v3.2.15
      default: true
    - name: ibm-resource-group
      alias: cs_resource_group
      version: v3.2.15
      variables:
        - name: provision
          value: false
    - name: ibm-activity-tracker
      alias: ibm-activity-tracker
      version: v2.4.15
    - name: ibm-cert-manager
      alias: ibm-cert-manager
      version: v1.1.0
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-flow-logs
      alias: ibm-flow-logs
      version: v1.0.1
      dependencies:
        - name: target
          ref: ibm-vpc
        - name: cos_bucket
          ref: flow_log_bucket
    - name: ibm-kms
      alias: kms
      version: v0.3.4
      variables:
        - name: provision
          value: false
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
          value: ''
      dependencies:
        - name: resource_group
          ref: kms_resource_group
    - name: ibm-kms-key
      alias: cos_key
      version: v1.5.2
      default: true
      variables:
        - name: provision
          value: true
      dependencies:
        - name: kms
          ref: kms
    - name: ibm-object-storage
      alias: cos
      version: v4.0.3
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-vpc
      alias: ibm-vpc
      version: v1.16.0
      variables:
        - name: address_prefix_count
          value: 3
        - name: address_prefixes
          value:
            - 10.1.0.0/20
            - 10.2.0.0/20
            - 10.3.0.0/20
    - name: ibm-object-storage-bucket
      alias: flow_log_bucket
      version: v0.8.3
      variables:
        - name: label
          value: flow-logs
        - name: allowed_ip
          value:
            - 0.0.0.0/0
    - name: ibm-vpc-gateways
      alias: ibm-vpc-gateways
      version: v1.9.0
    - name: ibm-vpc-ssh
      alias: vpc_ssh_bastion
      version: v1.7.1
      variables:
        - name: label
          value: bastion
    - name: ibm-vpc-subnets
      alias: int-ingress-subnets
      version: v1.13.2
      variables:
        - name: _count
          value: 3
        - name: label
          value: internal-ingress
        - name: ipv4_cidr_blocks
          value:
            - 10.1.0.0/26
            - 10.2.0.0/26
            - 10.3.0.0/26
      dependencies:
        - name: gateways
          ref: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      alias: bastion-subnets
      version: v1.13.2
      variables:
        - name: _count
          value: 3
        - name: label
          value: bastion
        - name: ipv4_cidr_blocks
          value:
            - 10.1.0.64/26
            - 10.2.0.64/26
            - 10.3.0.64/26
    - name: ibm-vpc-subnets
      alias: egress-subnets
      version: v1.13.2
      variables:
        - name: _count
          value: 3
        - name: label
          value: egress
        - name: ipv4_cidr_blocks
          value:
            - 10.1.0.128/26
            - 10.2.0.128/26
            - 10.3.0.128/26
    - name: ibm-vpc-subnets
      alias: ext-ingress-subnets
      version: v1.13.2
      variables:
        - name: _count
          value: 3
        - name: label
          value: external-ingress
        - name: ipv4_cidr_blocks
          value:
            - 10.1.0.192/26
            - 10.2.0.192/26
            - 10.3.0.192/26
    - name: ibm-vpc-vpn-gateway
      alias: ibm-vpc-vpn-gateway
      version: v1.1.4
      dependencies:
        - name: subnets
          ref: int-ingress-subnets
    - name: ibm-vpn-server
      alias: ibm-vpn-server
      version: v0.1.2
      dependencies:
        - name: subnets
          ref: int-ingress-subnets
        - name: ibm-cert-manager
          ref: cert-manager
    - name: vsi-bastion
      alias: vsi-bastion
      version: v1.10.0
      variables:
        - name: image_name
          scope: module
        - name: kms_enabled
          value: true
      dependencies:
        - name: subnets
          ref: bastion-subnets
        - name: vpcssh
          ref: vpc_ssh_bastion
  variables:
    - name: ibmcloud_api_key
      type: string
      description: The IBM Cloud api key
    - name: kms_resource_group_name
      type: string
      description: The name of the resource group
    - name: region
      type: string
    - name: vpc_resource_group_name
      type: string
      description: The name of the resource group
    - name: cs_resource_group_name
      type: string
      description: The name of the resource group
    - name: kms_region
      type: string
      description: Geographic location of the resource (e.g. us-south, us-east)
    - name: vpc_name_prefix
      type: string
      description: >-
        The name_prefix used to build the name if one is not provided. If used
        the name will be `{name_prefix}-{label}`
      defaultValue: base
    - name: vpc_ssh_bastion_public_key
      type: string
      description: >-
        The public key provided for the ssh key. If empty string is provided
        then a new key will be generated.
      defaultValue: ''
    - name: vpc_ssh_bastion_private_key
      type: string
      description: >-
        The private key provided for the ssh key. If empty string is provided
        then a new key will be generated.
      defaultValue: ''
    - name: vpc_ssh_bastion_public_key_file
      type: string
      description: >-
        The name of the file containing the public key provided for the ssh key.
        If empty string is provided then a new key will be generated.
      defaultValue: ''
    - name: vpc_ssh_bastion_private_key_file
      type: string
      description: >-
        The name of the file containing the private key provided for the ssh
        key. If empty string is provided then a new key will be generated.
      defaultValue: ''
    - name: int-ingress-subnets__count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 3
    - name: bastion-subnets__count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 3
    - name: egress-subnets__count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 3
    - name: ext-ingress-subnets__count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 3
