name: Verify

# Controls when the action will run.
on:
  workflow_call:
    outputs:
      status:
        description: The status of the job
        value: ${{ jobs.verify.outputs.status }}
    secrets:
      IBMCLOUD_API_KEY:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: quay.io/cloudnativetoolkit/cli-tools-ibmcloud:v1.2-v0.6.1
      options: --privileged --user root

    strategy:
      max-parallel: 2
      matrix:
        flavor:
          - quickstart
          - standard
        storage:
          - odf
      fail-fast: false

    env:
      HOME: /home/devops
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
      TF_VAR_purge_volumes: true
      TF_VAR_debug: true
      REGION: eu-gb
      TF_LOG_PROVIDER: INFO

    outputs:
      status: ${{ job.status }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Variables
        id: variables
        env:
          FLAVOR: ${{ matrix.flavor }}
          STORAGE: ${{ matrix.storage }}
        run: |
          RANDOM_PREFIX=$(echo $RANDOM | md5sum | head -c 5; echo)
          FLAVOR_CHAR=$(echo "${FLAVOR}" | fold -w ${1:-1} | head -n 1)
          STORAGE_CHAR=$(echo "${STORAGE}" | fold -w ${1:-1} | head -n 1)

          NAME_PREFIX="${FLAVOR_CHAR}${STORAGE_CHAR}-${RANDOM_PREFIX}-infra"
          
          echo "Name prefix: $NAME_PREFIX"
          echo "name-prefix=$NAME_PREFIX" >> "$GITHUB_OUTPUT"

      - name: Setup workspace - ${{ matrix.flavor }},${{ matrix.storage }}
        shell: bash
        env:
          NAME_PREFIX: ${{ steps.variables.outputs.name-prefix }}
          FLAVOR: ${{ matrix.flavor }}
          STORAGE: ${{ matrix.storage }}
        run: |
          id
          whoami
          
          cd main
          ./setup-workspace.sh -f "${FLAVOR}" -s "${STORAGE}" -n "${NAME_PREFIX}" -r "${REGION}" || exit 1
          
          cd ../workspaces/current
          
          echo ""
          echo "*** Start terraform.tfvars ***"
          cat cluster.tfvars
          cat gitops.tfvars
          echo "*** End terraform.tfvars ***"
          echo ""

      - name: Terraform Apply - ${{ matrix.flavor }},${{ matrix.storage }}
        shell: bash
        run: |
          cd ./workspaces/current
          
          ./apply.sh -a

      - name: Terraform Destroy - ${{ matrix.flavor }},${{ matrix.storage }}
        if: ${{ always() }}
        shell: bash
        run: |
          cd ./workspaces/current
          
          ./destroy.sh -a
