name: Verify

# Controls when the action will run.
on:
  workflow_call:
    outputs:
      status:
        description: The status of the job
        value: ${{ jobs.verify.outputs.status }}
    secrets:
      IBMCLOUD_API_KEY:
        required: true
      OPENSHIFT_SERVER:
        required: true
      OPENSHIFT_USER:
        required: true
      OPENSHIFT_PASSWORD:
        required: true
      GITHUB_PAT:
        required: true
      GITOPS_REPO_TOKEN:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install_runner:
    name: Install Runner
    runs-on: ubuntu-20.04

    steps:
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_username: ${{ secrets.OPENSHIFT_USER }}
          openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}

      - uses: redhat-actions/openshift-actions-runner-installer@v1
        with:
          github_pat: ${{ secrets.GITHUB_PAT }}     # Personal access token with organization permissions
          runner_image: quay.io/cloudnativetoolkit/github-terraform-runner
          runner_tag: cli-tools-ibmcloud
          runner_labels: cli-tools-ibmcloud
          runner_replicas: 2
          helm_extra_args: |
            --set-string secretName=github-pat-ibmcloud

  verify:
    needs: install_runner
    runs-on: [ self-hosted, cli-tools-ibmcloud ]

    strategy:
      matrix:
        flavor:
          - quickstart
        storage:
          - portworx
          - odf
      fail-fast: false

    env:
      HOME: /home/devops
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
      TF_VAR_purge_volumes: true
      TF_VAR_debug: true
      REGION: eu-de
      TF_VAR_gitops_repo_host: us-south.git.cloud.ibm.com
      TF_VAR_gitops_repo_org: cloud-native-toolkit-test
      TF_VAR_gitops_repo_username: seansund
      TF_VAR_gitops_repo_token: ${{ secrets.GITOPS_REPO_TOKEN }}

    outputs:
      status: ${{ job.status }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Variables
        id: variables
        env:
          FLAVOR: ${{ matrix.flavor }}
          STORAGE: ${{ matrix.storage }}
        run: |
          RANDOM_PREFIX=$(echo $RANDOM | md5sum | head -c 5; echo)
          FLAVOR_CHAR=$(echo "${FLAVOR}" | fold -w ${1:-1} | head -n 1)
          STORAGE_CHAR=$(echo "${STORAGE}" | fold -w ${1:-1} | head -n 1)

          NAME_PREFIX="${FLAVOR_CHAR}${STORAGE_CHAR}-${RANDOM_PREFIX}-infra"
          
          echo "Name prefix: $NAME_PREFIX"
          echo "::set-output name=name-prefix::$NAME_PREFIX"

      - name: Setup workspace - ${{ matrix.flavor }},${{ matrix.storage }}
        shell: bash
        env:
          NAME_PREFIX: ${{ steps.variables.outputs.name-prefix }}
          FLAVOR: ${{ matrix.flavor }}
          STORAGE: ${{ matrix.storage }}
        run: |
          id
          whoami
          
          cd main
          ./setup-workspace.sh -f "${FLAVOR}" -s "${STORAGE}" -n "${NAME_PREFIX}" -r "${REGION}" || exit 1
          
          cd ../workspaces/current
          
          echo ""
          echo "*** Start terraform.tfvars ***"
          cat cluster.tfvars
          echo "*** End terraform.tfvars ***"
          echo ""

      - name: Terraform Apply - ${{ matrix.flavor }},${{ matrix.storage }}
        shell: bash
        run: |
          cd ./workspaces/current
          
          ./apply.sh -a

      - name: Terraform Destroy - ${{ matrix.flavor }},${{ matrix.storage }}
        if: ${{ always() }}
        shell: bash
        run: |
          cd ./workspaces/current
          
          ./destroy.sh -a
