name: Verify

# Controls when the action will run.
on:
  workflow_call:
    outputs:
      status:
        description: The status of the job
        value: ${{ jobs.verify.outputs.status }}
    secrets:
      IBMCLOUD_API_KEY:
        required: true
      OPENSHIFT_SERVER:
        required: true
      OPENSHIFT_USER:
        required: true
      OPENSHIFT_PASSWORD:
        required: true
      GITHUB_PAT:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install_runner:
    name: Install Runner
    runs-on: ubuntu-20.04

    steps:
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_username: ${{ secrets.OPENSHIFT_USER }}
          openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}

      - uses: redhat-actions/openshift-actions-runner-installer@v1
        with:
          github_pat: ${{ secrets.GITHUB_PAT }}     # Personal access token with organization permissions
          runner_location: cloud-native-toolkit                              # Install organization level runners
          runner_image: quay.io/cloudnativetoolkit/github-terraform-runner
          runner_tag: cli-tools-ibmcloud
          runner_labels: openshift, cli-tools-ibmcloud

  verify:
    needs: install_runner
    runs-on: [ self-hosted, openshift, cli-tools-ibmcloud ]

    strategy:
      matrix:
        flavor:
          - quickstart
        storage:
          - portworx
          - odf
      fail-fast: false
      max-parallel: 1

    env:
      HOME: /home/devops
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
      TF_VAR_purge_volumes: true
      TF_VAR_debug: true
      REGION: eu-de
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

    outputs:
      status: ${{ job.status }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Terraform Apply - ${{ matrix.flavor }},${{ matrix.storage }}
        run: |
          RANDOM_PREFIX=$(cat /dev/urandom | tr -dc '[:alpha:]' | tr '[:upper:]' '[:lower:]' | fold -w ${1:-5} | head -n 1)
          FLAVOR_CHAR=$(echo "${{ matrix.flavor }}" | fold -w ${1:-1} | head -n 1)
          STORAGE_CHAR=$(echo "${{ matrix.storage }}" | fold -w ${1:-1} | head -n 1)
          
          cd main
          ./setup-workspace.sh -f ${{ matrix.flavor }} -s ${{ matrix.storage }} -n "${FLAVOR_CHAR}${STORAGE_CHAR}-${RANDOM_PREFIX}-infra" -r "${REGION}" || exit 1
          
          cd ../workspaces/current
          
          echo ""
          echo "*** Start terraform.tfvars ***"
          cat cluster.tfvars
          echo "*** End terraform.tfvars ***"
          echo ""
          
          ./apply.sh -a

      - name: Terraform Destroy - ${{ matrix.flavor }},${{ matrix.storage }}
        if: ${{ always() }}
        run: |
          echo "${PWD}"
          ls -l
          cd ./workspaces/current
          ./destroy.sh -a
