name: Verify

# Controls when the action will run.
on:
  workflow_call:
    outputs:
      status:
        description: The status of the job
        value: ${{ jobs.verify.outputs.status }}
    secrets:
      IBMCLOUD_API_KEY:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: quay.io/cloudnativetoolkit/cli-tools-ibmcloud:v1.2
      options: --privileged --user root

    strategy:
      matrix:
        flavor:
          #- quickstart
          - standard
        storage:
          #- portworx
          - odf
      fail-fast: false

    env:
      HOME: /home/devops
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      TF_VAR_ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
      TF_VAR_purge_volumes: true
      TF_VAR_debug: true
      REGION: eu-gb
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

    outputs:
      status: ${{ job.status }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Terraform Apply - ${{ matrix.flavor }},${{ matrix.storage }}
        run: |
          RANDOM_PREFIX=$(cat /dev/urandom | tr -dc '[:alpha:]' | tr '[:upper:]' '[:lower:]' | fold -w ${1:-5} | head -n 1)
          FLAVOR_CHAR=$(echo "${{ matrix.flavor }}" | fold -w ${1:-1} | head -n 1)
          STORAGE_CHAR=$(echo "${{ matrix.storage }}" | fold -w ${1:-1} | head -n 1)
          
          cd main
          ./setup-workspace.sh -f ${{ matrix.flavor }} -s ${{ matrix.storage }} -n "${FLAVOR_CHAR}${STORAGE_CHAR}-${RANDOM_PREFIX}-infra" -r "${REGION}" || exit 1
          
          cd ../workspaces/current
          
          echo ""
          echo "*** Start terraform.tfvars ***"
          cat cluster.tfvars
          cat gitops.tfvars
          echo "*** End terraform.tfvars ***"
          echo ""
          
          ./apply-all.sh -a

      - name: Terraform Destroy - ${{ matrix.flavor }},${{ matrix.storage }}
        if: ${{ always() }}
        run: |
          echo "${PWD}"
          ls -l
          cd ./workspaces/current
          ./destroy-all.sh -a
